name: bloc_pattern_drill
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #path
  data_layer:
    path: packages/data_layer
  domain_layer:
    path: packages/domain_layer

  #provider
  provider: ^6.0.4

  #get it
  get_it: ^7.2.0

  #local storage
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  #annotation
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

  #build
  freezed: ^2.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  #hive
  hive_generator: ^1.1.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
